
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://farhaanbukhsh.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /farhaanbukhsh.github.io

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

#force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Farhaan Bukhsh"
title: "{Farhaan Bukhsh}"
description: "This blog belongs to Farhaan, who is living to make a difference"
keywords: "farhaan, fedora, pagure. bukhsh, gsoc, dgplug, Jnaapti"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Sometimes not getting what you want is a beautiful stroke of luck!"
  - text: "Just Breathe!"
  - text: "Life isn't about finding yourself. Life is about creating yourself."
  - text: "There is no love sincerer than the love of food"
  - text: "As long as you can still grab a breath, you fight!"
  - text: "Life isn't about finding yourself. Life is about creating yourself."

me-img: "/img/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "farhaanbukhsh"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/gsoc.jpg"
    date: "May 2016"
    description: "Gsoc Happened"
  - image: "/img/timeline/dgplug.jpg"
    date: "May 2015"
    description: "Dgplug Happened"
  - image: "/img/timeline/jnaapti.jpg"
    date: "Dec 2014"
    description: "Jnaapti Happened"
  - image: "/img/timeline/hack.jpg"
    date: "Sep 2014"
    description: "Hacked my first"
  - image: "/img/timeline/exp.jpg"
    date: "Jan 2013 - Dec 2013"
    description: "Took time off to explore!"
  - image: "/img/timeline/ship.jpg"
    date: "Dec 2012"
    description: "Made Memories"
  - image: "/img/timeline/grad.jpg"
    date: "Dec 2012"
    description: "Completed Class XII"
  - image: "/img/timeline/champion.jpg"
    date: "Dec 2011"
    description: "Won Championship"
  - image: "/img/timeline/oath.jpg"
    date: "August 2011"
    description: "Took my first leadership oath!"
  - image: "/img/timeline/baby.jpg"
    date: "March  1994"
    description: "Cried my first"

# First image of the Timeline

timeline-img: "/img/timeline/me.png"

###########
# Contact #
###########

email: "farhaan.bukhsh@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Farhaan lives in Bangalore , a FOSS enthusiast and a proud Geek"
author_blurb_image: "/img/me.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/farhaan.bukhsh"
  - title: "twitter"
    url: "https://twitter.com/fhackdroid"
  - title: "github"
    url: "https://github.com/farhaanbukhsh"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
